#version 430

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// Struct for atom
struct AtomStruct
{
    vec3 center;
    float radius;
};

// SSBOs
layout(std430, binding = 0) buffer AtomsBuffer     { AtomStruct atom[]; };
layout(std430, binding = 1) buffer PositionsBuffer { vec3 pos[];   };

uniform int pnum;

void main() {
    // get particle index // TODO: check if the calculation is correct
    uint i = gl_GlobalInvocationID.x;
    if (i >= pnum) return;

    pos[i] = atom[i].center;
}
