#version 430 core

// Workgroup layout (just linear of atoms)
layout(local_size_x=8, local_size_y=1, local_size_z=1) in;

// Constant values
const int neighborsMaxCount = 6;

// Global variables
int cuttingFaceCount = 0;
vec3 cuttingFaceCenters[neighborsMaxCount];
float cuttingFaceRadii[neighborsMaxCount];
vec3 cuttingFaceNormals[neighborsMaxCount];
int endPointCount = 0;
vec3 endPoints[neighborsMaxCount];

// Uniforms
uniform int atomCount;
uniform float probeRadius;

// Structs
struct AtomStruct
{
    vec3 position;
    float radius;
};

// SSBOs
layout(std430, binding = 0) readonly restrict buffer AtomBuffer
{
    AtomStruct atoms[];
};

// Atomic counter
layout(binding = 1) uniform atomic_uint index;

// Image with output indices of surface atoms
layout(binding = 2, r32ui) restrict writeonly uniform uimageBuffer list;

// Main function
void main()
{
    // Index
    int atomIndex = int(gl_GlobalInvocationID.x);

    // Check whether in range
    if(atomIndex < atomCount)
    {
        // ### OWN VALUES ###

        // Own radius
        float atomRadius = atoms[atomIndex].radius;

        // Own position
        vec3 atomPosition = atoms[atomIndex].position;

        // Two times the probe radius
        float probeRadius2 = 2 * probeRadius;

        // ### ITERATION OVER ALL OTHER ATOMS TO BUILD UP CUTTING FACE LIST ###

        // Go over other atoms and build cutting face list
        for(int a = 0; a < atomCount; a++)
        {
            if(a == atomIndex) { continue; }

            // ### OTHER'S VALUES ###

            // Get values from other atom
            vec3 otherAtomPosition = atoms[a].position;
            float otherAtomRadius = atoms[a].radius;

            // ### INTERSECTION TEST ###

            // Vector from one center to other
            vec3 connection = otherAtomPosition - atomPosition;

            // Distance between extended atoms
            float atomDistance = length(connection);

            // Do they intersect? (TODO: think about equal..just add endpoint directly?)
            if(atomDistance >= (atomRadius + otherAtomRadius + probeRadius2))
            {
                continue;
            }

            // ### INTERSECTION AND CUTTING FACE LIST ###

            // Calculate center of intersection
            // http://gamedev.stackexchange.com/questions/75756/sphere-sphere-intersection-and-circle-sphere-intersection
            float h = 0.5 + ((atomRadius * atomRadius) - (otherAtomRadius * otherAtomRadius)) / (atomDistance * atomDistance);
            cuttingFaceCenters[cuttingFaceCount] = atomPosition + h * connection;

            // Calculate radius of intersection
            cuttingFaceRadii[cuttingFaceCount] = sqrt((atomRadius * atomRadius) - h * h* atomDistance * atomDistance);

            // Calculate normal of intersection
            cuttingFaceNormals[cuttingFaceCount] = normalize(connection);

            // Increment cutting face list index and break if max count of neighbors reached
            if((++cuttingFaceCount) == neighborsMaxCount)
            {
                break;
            }
        }

        // ### ITERATION OVER ALL CUTTING FACES TO BUILD UP END POINT LIST ###

        for(int c = 0; c < cuttingFaceCount; c++)
        {
            // Values of cutting face
            vec3 faceCenter = cuttingFaceCenters[c];
            float faceRadius = cuttingFaceRadii[c];
            vec3 faceNormal = cuttingFaceNormals[c];

            // Test every cutting face for intersection line with other
            for(int d = 0; d < cuttingFaceCount; d++)
            {
                if(c == d) { continue; }

                // Values of other cutting face
                vec3 otherFaceCenter = cuttingFaceCenters[d];
                float otherFaceRadius = cuttingFaceRadii[d];
                vec3 otherFaceNormal = cuttingFaceNormals[d];

                // Check for parallel (just not handle it :D)
                if(faceNormal == otherFaceNormal) { continue; }

                // Intersection of planes, resulting in line
                // http://stackoverflow.com/questions/6408670/line-of-intersection-between-two-planes

                // Direction of line
                vec3 lineDir = cross(faceNormal, otherFaceNormal);

                // Determinant (should be not zero since already check for parallelity)
                float lineDet = sqrt(length(lineDir));

                // Point on line
                linePoint =
                    ((cross(lineDir, otherFaceNormal) * length(faceCenter)
                    +(cross(FaceNormal, lineDir) * length(otherFaceCenter)))
                    / lineDet;

                // Intersection of line with sphere, resulting in endpoints
                // https://en.wikipedia.org/wiki/Line%E2%80%93sphere_intersection
                // TODO

                // Add endpoints to array

                // Increment count of end points
                endPointCount += 2;
            }

            // ### ITERATION OVER ALL END POINTS AND TEST WITH CUTTING FACES ###

            for(int e = endPointCount; e > 0 ; e--)
            {
                // Currently processed endpoint
                vec3 endPoint = endPoints[e];

                for(int c = 0; c < cuttingFaceCount; c++)
                {
                    vec3 vector = cuttingFaceCenters[c] - endPoint;
                    if(dot(vector, cuttingFaceNormals[d]) > 0)
                    {
                        // Throw away endpoint
                        endPointCount--;
                        continue;
                    }
                }
            }

            // ### CHECK FOR EMPTY END POINT ARRAY ###

            // When there was no cut it is also a surface atom
            if(endPointCount == 0 && cuttingFaceCount == 0)
            {
                // Increment atomic counter
                uint idx = atomicCounterIncrement(index);

                // Save index of atom at index of atomic counter in image
                imageStore(list, int(idx), uvec4(gl_GlobalInvocationID.x));
            }
        }
    }
};
